import Link from "next/link";
import { LegalOperatorDisclosure } from "@/components/legal-operator-disclosure";
import { PulsercuitBrand } from "@/components/pulsercuit-brand";

export const metadata = { title: "Rewards Policy" };
export const dynamic = "force-dynamic";

export default function RewardsPolicyPage() {
  return <main className="completion-page">
    <header className="completion-header shell"><PulsercuitBrand /><nav><Link href="/proof">Proof</Link><Link href="/support">Help</Link><Link href="/privacy">Privacy</Link></nav></header>
    <section className="completion-hero shell"><span className="section-kicker">Rewards policy</span><h1>Rewards only move after verification.</h1><p>Eligibility, funding, verification and payout are separate steps. A screen alone never creates a reward or payment.</p></section><section className="completion-card shell"><span className="app-eyebrow">Quick summary</span><h2>Verified reward → available balance → protected payout.</h2><p>Pulse requires an open window and funded reward. Extra rewards require verified completion. Reversed qualifying activity can reverse linked rewards. A payout is reserved before it is sent so the same balance cannot be paid twice.</p></section>
    <article className="policy-body shell">
      <LegalOperatorDisclosure />
      <h2>Base Pulse</h2><p>The currently active base Pulse uses the configured fixed reward. An eligible claim can be released only when its rolling interval has opened, human verification succeeds, account risk is within the current safety policy and the configured reward treasury has enough real budget. If the treasury is closed, exhausted or safety-limited, no reward is promised and no balance is changed.</p><h2>Variable Pulse mode</h2><p>A variable free-reward mode may be introduced only when Pulsercuit explicitly enables it and publishes the applicable reward range and probabilities. It must not require a purchase, payment or paid action to improve the chance of a Pulse result. Until that mode is enabled, the fixed base reward remains authoritative. Jurisdictional restrictions can keep variable rewards unavailable in some locations.</p>
      <h2>Rolling eligibility</h2><p>The next eligibility window is measured from the previous successful Pulse claim rather than from a calendar-hour boundary. This prevents two claims from being created by claiming immediately before and after a clock boundary.</p>
      <h2>Earn actions</h2><p>Earn actions are optional. For provider-backed or direct opportunities, browser activity alone never creates balance. The required authoritative callback or campaign settlement event must confirm the action before Pulsercuit credits the reward. Ordinary sponsored-ad clicks are not paid user actions.</p>
      <h2>Credits and displayed value</h2><p>Credits are the internal ledger unit. Displayed currency values are explanatory views of configured reward and payout packs; they do not create a separate claim outside the ledger.</p>
      <h2>Pending, available and withdrawn states</h2><p>Rewards may pass through different states before becoming available. Withdrawals reserve the required credits before an external payout is attempted so the same balance cannot be spent twice.</p>
      <h2>Reversals</h2><p>If an authoritative provider reverses or charges back a qualifying Turbo conversion, Pulsercuit may reverse the linked ledger reward and any dependent referral reward. The reversal remains visible in history.</p>
      <h2>Network rewards</h2><p>A registration or recruitment event by itself does not qualify for a network monetary reward. Direct referral or deeper-level rewards, when enabled, require verified eligible economic activity under the displayed rule. Network commission is calculated from eligible platform contribution rather than by reducing another member&apos;s displayed reward, and a reversal of the source event can reverse dependent network rewards.</p><h2>Cashback</h2><p>Cashback can remain pending while a partner verifies an eligible purchase or transaction. Only confirmed cashback becomes available balance. Cancellation, refund, chargeback or attribution reversal can reverse the linked cashback entry.</p><h2>XP and missions</h2><p>XP, ranks and mission progress recognize verified participation. They are non-monetary product signals, are not withdrawable credits and do not by themselves create a cash claim.</p>
      <h2>Missing rewards</h2><p>If an eligible Pulse or completed Turbo does not appear, open an Earning case in the <Link href="/support">Help Center</Link>. Include the approximate time and any visible reference so the event can be reconciled.</p>
      <h2>Payouts</h2><p>A payout is complete only after the configured payout provider returns an authoritative successful result. Ambiguous outcomes remain reserved and reuse the original payout identity on safe retry rather than creating a duplicate payment. Where a Withdrawal Pass is active, one fee-free window and any optional extra-withdrawal fee are determined before reservation; an extra fee must be reversible if the associated withdrawal fails.</p>
      <h2>Public proof</h2><p><Link href="/proof">Pulsercuit Proof</Link> reports aggregate production facts and deliberately distinguishes rewards credited to the internal ledger from withdrawals actually completed by the payout provider.</p>
    </article>
    <footer className="completion-footer shell"><span>Pulsercuit</span><div><Link href="/proof">Proof</Link><Link href="/terms">Terms</Link><Link href="/privacy">Privacy</Link><Link href="/support">Support</Link></div></footer>
  </main>;
}
